### PR TITLE
feat: rework epxorted providers and hooks and update docs

### PR DESCRIPTION
**Pull request by mkarajohn**
Resolves [DSTRBTN-540]

<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>

> ## TL;DR
> This pull request includes changes to several files in the codebase. It adds two new files, modifies existing files, and updates documentation. The changes involve adding new types, functions, and hooks related to authentication, organizations, and Orfium products. The pull request also includes updates to the sidebar position in the documentation files.
> 
> ## What changed
> - Added two new files: OrfiumProductsContextValue.mdx and OrganizationsContextValue.mdx
> - Modified existing files: AuthenticationContextValue.md, useAuthentication.mdx, useData.md, API hooks documentation files
> - Updated sidebar position in documentation files
> 
> ## How to test
> - Review the changes made to the code files
> - Test the new functions and hooks related to authentication, organizations, and Orfium products
> - Verify the updates to the documentation files
> 
> ## Why make this change
> - Add new functionality related to authentication, organizations, and Orfium products
> - Improve the documentation and organization of the codebase
> - Enhance the user experience and provide more flexibility in managing authentication and accessing Orfium's single sign-on mechanism
</details>

[DSTRBTN-540]: https://orfium.atlassian.net/browse/DSTRBTN-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mkarajohn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #74** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/74" target="_blank">Graphite</a> 
    * **PR #75** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/75" target="_blank">Graphite</a> 
      * **PR #76** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/76" target="_blank">Graphite</a> 
        * **PR #77** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/77" target="_blank">Graphite</a> 
          * **PR #78** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/78" target="_blank">Graphite</a> 
            * **PR #79** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/79" target="_blank">Graphite</a> 
              * **PR #80** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/80" target="_blank">Graphite</a> 
                * **PR #81** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/81" target="_blank">Graphite</a> 
                  * **PR #82** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/82" target="_blank">Graphite</a> 
                    * **PR #83** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/83" target="_blank">Graphite</a> 
                      * **PR #85** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/85" target="_blank">Graphite</a> 
                        * **PR #86** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/86" target="_blank">Graphite</a> 
                          * **PR #87** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/87" target="_blank">Graphite</a> 
                            * **PR #88** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/88" target="_blank">Graphite</a> 
                              * **PR #89** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/89" target="_blank">Graphite</a> 
                                * **PR #90** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/90" target="_blank">Graphite</a> 
                                  * **PR #91** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/91" target="_blank">Graphite</a> 
                                    * **PR #92** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/92" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Orfium/toolbox/92?utm_source=stack-comment).

**Comment by mkarajohn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #74** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/74" target="_blank">Graphite</a> 
    * **PR #75** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/75" target="_blank">Graphite</a> 
      * **PR #76** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/76" target="_blank">Graphite</a> 
        * **PR #77** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/77" target="_blank">Graphite</a> 
          * **PR #78** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/78" target="_blank">Graphite</a> 
            * **PR #79** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/79" target="_blank">Graphite</a> 
              * **PR #80** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/80" target="_blank">Graphite</a> 
                * **PR #81** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/81" target="_blank">Graphite</a> 
                  * **PR #82** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/82" target="_blank">Graphite</a> 
                    * **PR #83** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/83" target="_blank">Graphite</a> 
                      * **PR #85** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/85" target="_blank">Graphite</a> 
                        * **PR #86** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/86" target="_blank">Graphite</a> 
                          * **PR #87** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/87" target="_blank">Graphite</a> 
                            * **PR #88** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/88" target="_blank">Graphite</a> 
                              * **PR #89** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/89" target="_blank">Graphite</a> 
                                * **PR #90** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/90" target="_blank">Graphite</a> 
                                  * **PR #91** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/91" target="_blank">Graphite</a> 
                                    * **PR #92** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/92" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Orfium/toolbox/92?utm_source=stack-comment).

**Comment by mkarajohn** [comment]
Current dependencies on/for this PR:
* master
  * **PR #74** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/74" target="_blank">Graphite</a> 
    * **PR #75** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/75" target="_blank">Graphite</a> 
      * **PR #76** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/76" target="_blank">Graphite</a> 
        * **PR #77** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/77" target="_blank">Graphite</a> 
          * **PR #78** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/78" target="_blank">Graphite</a> 
            * **PR #79** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/79" target="_blank">Graphite</a> 
              * **PR #80** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/80" target="_blank">Graphite</a> 
                * **PR #81** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/81" target="_blank">Graphite</a> 
                  * **PR #82** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/82" target="_blank">Graphite</a> 
                    * **PR #83** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/83" target="_blank">Graphite</a> 
                      * **PR #85** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/85" target="_blank">Graphite</a> 
                        * **PR #86** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/86" target="_blank">Graphite</a> 
                          * **PR #87** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/87" target="_blank">Graphite</a> 
                            * **PR #88** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/88" target="_blank">Graphite</a> 
                              * **PR #89** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/89" target="_blank">Graphite</a> 
                                * **PR #90** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/90" target="_blank">Graphite</a> 
                                  * **PR #91** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/91" target="_blank">Graphite</a> 
                                    * **PR #92** <a href="https://app.graphite.dev/github/pr/Orfium/toolbox/92" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Orfium/toolbox/92?utm_source=stack-comment).

**Review by panvourtsis — APPROVED** [review]

**Comment by mkarajohn** [comment]
### Merge activity

* **Oct 24, 10:43 AM**: @mkarajohn started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Orfium/toolbox/92).

**Pull request merged**
