### PR TITLE
[DVP-189] Fix/ Switch organization

### PR DESCRIPTION
**Pull request by Christos-Zacharopoulos**
## Description

In this PR:

1. `auth0-spa-js` is updated to latest version
2. the bug on switching organizations is fixed
3. ~the bug on prettier where it deletes imports is fixed by removing the prettier plugin `prettier-plugin-organize-imports`~ ❌ (not relevant to this PR anymore)

## Test Plan

All tests that were impacted have been changed accordingly

### CODE REVIEW

**Comment by mkarajohn** [comment]
>the bug on prettier where it deletes imports is fixed by removing the prettier plugin prettier-plugin-organize-imports

What bug is this, where is it reported? The plugin removes imports if they are not used. If this is all it does it's not a bug and I would argue against removing it.

**Comment by mkarajohn** [comment]
> https://youtrack.jetbrains.com/issue/WEB-50178/Code-reformat-with-prettier-and-prettier-plugin-organize-imports-deletes-imports-if-Optimize-imports-is-enabled

For the record I cannot reproduce this, following the steps mentioned in the issue. 

>PyCharm 2023.2.1 (Professional Edition)
>Build #PY-232.9559.58, built on August 22, 2023

>I have the same exact functionality ( removing unused imports )

The thing is it does not only remove unused imports, it also sorts them. 

Before removing it have you tried

* turning off Webstorm's "Optimize imports" since the issue explicitly states it happens when that option is enabled (with the plugin enabled the native "Optimize imports" should not be needed anyway)
* setting `organizeImportsSkipDestructiveCodeActions` to `true` instead of `false`

and see if any of these resolves the issue?

**Comment by Christos-Zacharopoulos** [comment]
> Before removing it have you tried
> 
> * turning off Webstorm's "Optimize imports" since the issue explicitly states it happens when that option is enabled (with the plugin enabled the native "Optimize imports" should not be needed anyway)
> * setting `organizeImportsSkipDestructiveCodeActions` to `true` instead of `false`
> 
> and see if any of these resolves the issue?

- Yes
- and yes.

In the second case it imports like `import React from "react";` but removes ts-ignore and doesn't change the sorting of import.

**Comment by panvourtsis** [comment]
i reverted the prettier change as it's a dev tool we use and this fix doesn't have to be kept back because of it. Lets revisit on another PR

**Review by panvourtsis — APPROVED** [review]

**Review by panvourtsis — APPROVED** [review]

**Pull request merged**
